library(graphics)
head(mtcars)
lm(mpg~wt, data=mtcars)
lmfit <- lm(mpg~wt, data=mtcars)
summary(lmfit)
plot(lmfit)
plot(mpg~wt, data=mtcars)
summary(mtcars)
write.csv(mtcars, 'mtcars01.csv')
hist(mtcars01$mpg)
help.start()
help(package='vcd')
help(Arthritis)
Arthritis
example(Arthritis)
example(Arthritis)
q()
q()
head(Arthritis)
x<- matrix(1:10, nrow=2, byrow= T)
summary(mtcars$mpg)
plot(mtcars$mpg, mtcars$disp)
plot(mtcars$mpg, mtcars$wt)
attach (mtcars)
summary(mpg)
plot(mpg, disp)
